group=sh.harold.library
version=v10
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.configureondemand=true

paperApiVersion=26.2.build.112-stable
paperMinecraftVersion=26.2
paper12111ApiVersion=1.21.11-R0.1-SNAPSHOT
paper12111MinecraftVersion=1.21.11
spigot188ApiVersion=1.8.8-R0.1-SNAPSHOT
adventurePlatformBukkitVersion=4.4.1
velocityApiVersion=3.3.0-SNAPSHOT
minestomVersion=2026.03.03-1.21.11
adventureVersion=4.17.0
junitVersion=5.11.3
caffeineVersion=3.1.8
snakeyamlVersion=2.2
mongodbDriverVersion=5.1.4
testcontainersVersion=1.20.4
packetEventsVersion=2.13.0
jomlVersion=1.10.8

minecraftVersion=26.2
fabricLoaderVersion=0.19.3
fabricApiVersion=0.155.2+26.2

fabric12111MinecraftVersion=1.21.11
fabric12111LoaderVersion=0.18.6
fabric12111ApiVersion=0.141.3+1.21.11
