rootProject.name = "library"

include(
    ":common:tick-lifecycle-api",
    ":common:spatial-api",
    ":common:spatial-core",
    ":common:tween-api",
    ":common:tween-core",
    ":common:curve-api",
    ":common:curve-core",
    ":common:telegraph-api",
    ":common:telegraph-core",
    ":common:trajectory-preview-api",
    ":common:trajectory-preview-core",
    ":common:impulse-api",
    ":common:impulse-core",
    ":common:ambient-zone-api",
    ":common:ambient-zone-core",
    ":common:camera-motion-api",
    ":common:camera-motion-core",
    ":common:data-api",
    ":common:data-memory",
    ":common:cooldown-api",
    ":common:cooldown-core",
    ":common:ui-values-api",
    ":common:screen-overlay-api",
    ":common:screen-overlay-core",
    ":common:message-api",
    ":common:message-core",
    ":common:sound-api",
    ":common:sound-core",
    ":common:state-machine-api",
    ":common:state-machine-core",
    ":common:menu-api",
    ":common:menu-core",
    ":common:entity-api",
    ":common:entity-core",
    ":common:house-service-entity",
    ":platform:paper:message-paper",
    ":platform:paper:sound-paper",
    ":platform:paper:camera-motion-paper",
    ":platform:paper:screen-overlay-paper",
    ":platform:paper:telegraph-paper",
    ":platform:paper:trajectory-preview-paper",
    ":platform:paper:impulse-paper",
    ":platform:paper:ambient-zone-paper",
    ":platform:paper:menu-paper",
    ":platform:paper:paper-example",
    ":platform:paper:entity-paper",
    ":platform:paper:entity-paper-citizens",
    ":platform:paper:paper-entity-example",
    ":platform:minestom:message-minestom",
    ":platform:minestom:sound-minestom",
    ":platform:minestom:camera-motion-minestom",
    ":platform:minestom:screen-overlay-minestom",
    ":platform:minestom:telegraph-minestom",
    ":platform:minestom:trajectory-preview-minestom",
    ":platform:minestom:impulse-minestom",
    ":platform:minestom:ambient-zone-minestom",
    ":platform:minestom:menu-minestom",
    ":platform:minestom:minestom-example",
    ":platform:minestom:entity-minestom",
    ":platform:minestom:minestom-entity-example",
    ":platform:velocity:message-velocity",
    ":platform:velocity:velocity-example",
)

dependencyResolutionManagement {
    repositoriesMode.set(org.gradle.api.initialization.resolve.RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        mavenCentral()
        maven("https://repo.papermc.io/repository/maven-public/")
        maven("https://maven.citizensnpcs.co/repo")
        maven("https://repo.minebench.de")
    }
}
