name: paper-entity-example
version: '${version}'
main: sh.harold.library.example.paper.entity.PaperEntityExamplePlugin
api-version: '26.2'
folia-supported: true
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
